set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/modules)
message(STATUS "init my project...")
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)